[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_staking = "BZ9CvYyMP6yHpE5DxDgPg9pXjq2U7u4jb6tEXjotcu29"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
